### PR TITLE
[ISSUE #282] Fix the issue that DLedger RPC Service thread stuck

### LINKED ISSUE #282: DLedger RPC Service thread stuck
The following phenomena were found in our test environment

Three nodes, one node down, unable to select a leader. We found one of the DLedger nodes cannot process any rpc requests (it is candidate role), and all NettyServerPublicExecutor threads are stuck in the handlePush method

image

The number of queued tasks is increasing, but the number of completed tasks has not changed

image

The thread stuck in here, because the blocking queue is already full.

image

image

However, since it is a candidate, it will no longer peek data from the blocking queue

image

### PR DESCRIPTION
**Pull request by RongtongJin**
Fix #282 
Fix the issue that DLedger RPC Service thread stuck

### CODE REVIEW

**Review by TheR1sing3un — APPROVED** [review]
LGTM~

File: dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java [hunk 1]
```diff
@@ -380,21 +381,17 @@ public void doWork() {
...
+     * request, but if the append requests are few and scattered, the leader will send a pure request to inform the
+     * follower of committed index.
      * <p>
      * The common transferring between these types are as following:
      * <p>
-     * COMPARE ---- TRUNCATE ---- APPEND ---- COMMIT
-     * ^                             |
-     * |---<-----<------<-------<----|
+     * COMPARE ---- TRUNCATE ---- APPEND ---- COMMIT ^                             | |---<-----<------<-------<----|
      */
```
Comment (mxsm) [inline dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java:395]: fix doc style

**Review by mxsm — APPROVED** [review]
LGTM~
